### ISSUE TITLE
First steps

### ISSUE THREAD

**Issue by HealthyPear** [cta-observatory/pyirf#4]
This is a **summary issue**.

These are some of what appear to be first things that should be address:

- [ ] Data formats
   - [x] input DL2 data format (#2 , #5 )
   - [ ] output IRF data format (#6 )
- [ ] Reproduce current EventDisplay IRFs
   - [x] on-axis (#7 )
   - [ ] off-axis
      - [ ] add diffuse test data (#54) 

Dedicated issues should be opened and linked here.

**Comment by maxnoe** [comment]
First steps have been done.

**Comment by HealthyPear** [comment]
also this is technically not finished, I made a list for what I considered first steps but we could just rename it like "list of reference test analysis"
